### ISSUE TITLE
Other overlays break editing and line rendering

### ISSUE THREAD

**Issue by dyamito** [cursorless-everywhere/emacs-cursorless#2]
Using company-mode for example causes weird things to happen when typing
![2022-08-30-202304_1530x1219_scrot](https://user-images.githubusercontent.com/106293442/187566375-7bc06df8-9300-4343-bea9-33eb41aa73ad.png)

The overlay creates a huge empty gap, and continuing to type moves the cursor all over. For now I toggled on child frames for autocompletion, but I imagine this will come up again.

**Comment by rntz** [comment]
Yeah, I imagine this will be a problem, I'm just really not sure how to deal with it. The way the hat rendering works is that we add an overlay to every line which puts a fake line above it, and we fill this line with an SVG containing the hats. These hats are positioned via dead-reckoning: multiply character width by column. This is extremely janky and prone to breakage; this is also why line numbers don't work. Unfortunately I don't know of a less janky way of drawing arbitrary svgs over specific characters.

The ideal way would be to add an overlay to those characters specifically that causes them to get rendered differently. However, while overlays can replace text with an image, they can't draw an image over/under/above the existing text.

One idea early on was to replace letters by an image of those letters with a hat above them. But this means we need to replicate all emacs face attribute effects, like underline, overline, changing faces, reverse video, etc etc. Seems hard and janky.

Another possibility is to patch emacs to allow overlays to draw over text instead of merely replacing it. No idea how easy this should be, and it requires an emacs fork.

Any ideas?

**Comment by dyamito** [comment]
I've been doing a bit of a deep dive on this stuff, fonts in particular. To summarize my understanding of the state of the possible approaches:

1) Fake lines
   This is the current approach. It's reasonably performant as far as I can tell, and it looks nice. The downside is of course how functional it is. I've already run into several weird scenarios with it. Maybe we can try to patch over specific issues that come up, but the fact that we're already hitting several problems is a bit alarming.

2) Fake characters
   This is a "create an SVG" that looks like the character and overlay it. I played around with this a bit and think I could get something that looks reasonable while keeping the other overlays intact. The catch is the SVGs would have to be pregenerated from fonts (this is annoying but doable with a python script). This would create a "compile" step, but it might make the rest of the problems go away. The biggest concern I have is with performance. The fake lines approach only creates one SVG per *line*, but the character approach would be per character. Some preliminary testing makes me think it's possible, but certainly not a sure thing.
   
3) Font Frenzy
   I thought about writing a script that took a font and generated a new font for each (color, shape) pair. This would let us use text properties to set different characters to different fonts. For example, a character would use the helvetica-blue-bolt font and the one next to it the helvetica-yellow-fox font. It sounds wacky, but I think it would be functional and performant at the cost of moving hat styling to a compile time option. Unfortunately, it looks like we would need "color fonts" and support for these is all over the place. I'm still not entirely sure what more to look into, but I don't think it's possible to do at this point. A particular sticking point is that the hat and the character would have to be different colors -- it's not obvious how to do this. Someone who understands fonts, cairo, and the display support story in emacs might be able to dig further, but I think I'm at a dead end for the moment.
   
4) Abandon hats
   Abandon hats and rely on built-in emacs text styling. Options are [limited](https://www.gnu.org/software/emacs/manual/html_node/elisp/Face-Attributes.html) but performant and simple - underlines (line/wave), overlines, boxes, background colors, foreground colors, sadness. Conflicts with other libraries would be a problem, e.g. how do we underline something for cursorless when flycheck is underlining it as an error?

5) Patch/contribute to Emacs
   I'm not very optimistic about this. I'm unsure what diving into the codebase of Emacs looks like, and I find it hard to believe we could add support for more general text decorations. As for a random data point, this is what adding support for wavy underlines looked like (about a decade ago) - https://github.com/emacs-mirror/emacs/commit/9b0e3ebaef5aed8097965b14c97a0579763be7fd#diff-7a2ab21884efa4485e91f4b4a7fd7a8e35a8ec6e9ce6470a47dc62161a0e3790.

**Comment by dyamito** [comment]
For posterity, I implemented approach 5 and it appears to be working pretty well. It lives on this branch: https://github.com/emacs-mirror/emacs/compare/master...dyamito:emacs:cursorless.

**Comment by ErikPrantare** [comment]
I have implemented approach 2: https://github.com/ErikPrantare/hatty.el

The upside of this is that it does not require maintaining a custom fork of Emacs.

How difficult would it be to wire up this project to use it?  I would be happy to make any additions to hatty necessary for making it possible.
